from django.contrib import admin
from cloudmeb.receipt_bank_txts.models import Receipt_bank_txt
from django.utils.translation import ugettext_lazy as _

class Receipt_bank_txtAdmin(admin.ModelAdmin):
    fileds = ('receipt_bank_txt_name', 'receipt_bank_txt_header_title_en', 'receipt_bank_txt_header_title_fr', 'receipt_bank_txt_header_subtitle_en', 'receipt_bank_txt_header_subtitle_fr', 'receipt_bank_txt_why_title_en', 'receipt_bank_txt_why_title_fr', 'receipt_bank_txt_freeintroduce_title_en', 'receipt_bank_txt_freeintroduce_title_fr', 'receipt_bank_txt_freeintroduce_text_en', 'receipt_bank_txt_freeintroduce_text_fr', 'receipt_bank_txt_supercharge_title_en', 'receipt_bank_txt_supercharge_title_fr', 'receipt_bank_txt_supercharge_subtitle1_en', 'receipt_bank_txt_supercharge_subtitle1_fr', 'receipt_bank_txt_supercharge_subtext1_en', 'receipt_bank_txt_supercharge_subtext1_fr', 'receipt_bank_txt_supercharge_subtitle2_en', 'receipt_bank_txt_supercharge_subtitle2_fr', 'receipt_bank_txt_supercharge_subtext2_en', 'receipt_bank_txt_supercharge_subtext2_fr', 'receipt_bank_txt_supercharge_subtitle3_en', 'receipt_bank_txt_supercharge_subtitle3_fr', 'receipt_bank_txt_supercharge_subtext3_en', 'receipt_bank_txt_supercharge_subtext3_fr', 'receipt_bank_txt_how_work_title_en', 'receipt_bank_txt_how_work_title_fr', 'receipt_bank_txt_start_now_title_en', 'receipt_bank_txt_start_now_title_fr', 'receipt_bank_txt_application_free_header_en', 'receipt_bank_txt_application_free_header_fr', 'receipt_bank_txt_application_free_subheader_en', 'receipt_bank_txt_application_free_subheader_fr', 'receipt_bank_txt_application_header_en', 'receipt_bank_txt_application_header_fr', 'receipt_bank_txt_application_subheader_en', 'receipt_bank_txt_application_subheader_fr',)
    list_display = ('receipt_bank_txt_name', 'receipt_bank_txt_header_title_en', 'receipt_bank_txt_header_title_fr', 'receipt_bank_txt_header_subtitle_en', 'receipt_bank_txt_header_subtitle_fr', 'receipt_bank_txt_why_title_en', 'receipt_bank_txt_why_title_fr', 'receipt_bank_txt_freeintroduce_title_en', 'receipt_bank_txt_freeintroduce_title_fr', 'receipt_bank_txt_freeintroduce_text_en', 'receipt_bank_txt_freeintroduce_text_fr', 'receipt_bank_txt_supercharge_title_en', 'receipt_bank_txt_supercharge_title_fr', 'receipt_bank_txt_supercharge_subtitle1_en', 'receipt_bank_txt_supercharge_subtitle1_fr', 'receipt_bank_txt_supercharge_subtext1_en', 'receipt_bank_txt_supercharge_subtext1_fr', 'receipt_bank_txt_supercharge_subtitle2_en', 'receipt_bank_txt_supercharge_subtitle2_fr', 'receipt_bank_txt_supercharge_subtext2_en', 'receipt_bank_txt_supercharge_subtext2_fr', 'receipt_bank_txt_supercharge_subtitle3_en', 'receipt_bank_txt_supercharge_subtitle3_fr', 'receipt_bank_txt_supercharge_subtext3_en', 'receipt_bank_txt_supercharge_subtext3_fr', 'receipt_bank_txt_how_work_title_en', 'receipt_bank_txt_how_work_title_fr', 'receipt_bank_txt_start_now_title_en', 'receipt_bank_txt_start_now_title_fr', 'receipt_bank_txt_application_free_header_en', 'receipt_bank_txt_application_free_header_fr', 'receipt_bank_txt_application_free_subheader_en', 'receipt_bank_txt_application_free_subheader_fr', 'receipt_bank_txt_application_header_en', 'receipt_bank_txt_application_header_fr', 'receipt_bank_txt_application_subheader_en', 'receipt_bank_txt_application_subheader_fr',)

admin.site.register(Receipt_bank_txt, Receipt_bank_txtAdmin)  
